;; Terrific Audio Driver (TAD) v0.2.0 — WLA-DX Integration
;;
;; Ported from the official ca65/64tass API by undisbeliever (Marcus Rowe).
;; Original license: Zlib. See tools/tad/TAD_LICENSE.md.
;;
;; This file provides constants, WRAM variables, and audio data embedding
;; for the TAD audio driver on SNES HiROM+FastROM.
;;
;; IMPORTANT: After changing audio content (songs, samples, SFX), re-run:
;;   tools/tad/tad-compiler.exe 64tass-export --hirom \
;;     --output-asm build/audio/tad-audio-data.asm \
;;     --output-bin build/audio/tad-audio-data.bin \
;;     --output-inc build/audio/tad-enums.inc \
;;     --section "AudioData0" audio/smi.terrificaudio
;; Then update the SIZE/OFFSET defines below from the generated .asm output.

.include "src/config/config.inc"


; =========
; Constants
; =========

; TAD IO protocol version (must match audio-driver binary)
.define TAD_IO_VERSION 20

; Address in Audio-RAM where the loader is placed
.define TAD_LOADER_ARAM_ADDR $0200

; Default transfer bytes per Tad_Process call
.define TAD_MIN_TRANSFER_PER_FRAME 32
.define TAD_MAX_TRANSFER_PER_FRAME 800
.define TAD_DEFAULT_TRANSFER_PER_FRAME 256

; Maximum pan value
.define TAD_MAX_PAN 128
.define TAD_CENTER_PAN 64


; --- TadFlags bits ---
.define TadFlags_RELOAD_COMMON_AUDIO_DATA  $80
.define TadFlags_PLAY_SONG_IMMEDIATELY     $40
.define TadFlags_RESET_GLOBAL_VOLUMES      $20
.define TAD_ALL_FLAGS (TadFlags_RELOAD_COMMON_AUDIO_DATA | TadFlags_PLAY_SONG_IMMEDIATELY | TadFlags_RESET_GLOBAL_VOLUMES)

; Default flags: play songs immediately + reset global volumes on common
; audio data load (otherwise the SPC driver boots with global SFX / music
; volume at 0, SFX voices key on but envelope stays silent).
.define TAD_DEFAULT_FLAGS (TadFlags_PLAY_SONG_IMMEDIATELY | TadFlags_RESET_GLOBAL_VOLUMES)

; --- TadAudioMode ---
.define TadAudioMode_MONO     0
.define TadAudioMode_STEREO   1
.define TadAudioMode_SURROUND 2
.define TAD_N_AUDIO_MODES 3
.define TAD_DEFAULT_AUDIO_MODE TadAudioMode_MONO


; --- TadState ---
.define TadState_NULL                       $00
.define TadState_WAITING_FOR_LOADER_COMMON  $7b
.define TadState_WAITING_FOR_LOADER_SONG    $7c
.define TadState_LOADING_COMMON_AUDIO_DATA  $7d
.define TadState_LOADING_SONG_DATA_PAUSED   $7e
.define TadState_LOADING_SONG_DATA_PLAY     $7f
.define TadState_PAUSED                     $80
.define TadState_PLAYING_SFX                $81
.define TadState_PLAYING                    $82

.define TAD__FIRST_WAITING_STATE      TadState_WAITING_FOR_LOADER_COMMON
.define TAD__FIRST_LOADING_STATE      TadState_LOADING_COMMON_AUDIO_DATA
.define TAD__FIRST_LOADING_SONG_STATE TadState_LOADING_SONG_DATA_PAUSED


; --- TadCommand ---
.define TadCommand_PAUSE                 0
.define TadCommand_PAUSE_MUSIC_PLAY_SFX  2
.define TadCommand_UNPAUSE               4
.define TadCommand_PLAY_SOUND_EFFECT     6
.define TadCommand_STOP_SOUND_EFFECTS    8
.define TadCommand_SET_MAIN_VOLUME       10
.define TadCommand_SET_MUSIC_CHANNELS    12
.define TadCommand_SET_SONG_TIMER        14
.define TadCommand_SET_GLOBAL_MUSIC_VOL  16
.define TadCommand_SET_GLOBAL_SFX_VOL    18
.define TadCommand_SET_GLOBAL_VOLUMES    20


; --- IO Ports (S-CPU → S-SMP) ---
.define TadIO_COMMAND_PORT          $2140
.define TadIO_COMMAND_MASK          %00011110
.define TadIO_COMMAND_I_MASK        %11100001
.define TadIO_PARAMETER0_PORT       $2141
.define TadIO_PARAMETER1_PORT       $2142
.define TadIO_SWITCH_TO_LOADER_PORT $2143
.define TadIO_SWITCH_TO_LOADER_BIT  5
.define TadIO_SWITCH_TO_LOADER      ($80 | (1 << TadIO_SWITCH_TO_LOADER_BIT))

; --- IO Ports (S-SMP → S-CPU) ---
.define TadIO_COMMAND_ACK_PORT      $2140
.define TadIO_MODE_PORT             $2141
.define TadIO_MODE_IPL              $bb
.define TadIO_MODE_LOADER           $4c
.define TadIO_MODE_AUDIO_DRIVER     $61

; --- Loader Init handshake ---
.define TadIO_LI_DATA_TYPE_PORT     $2141
.define TadIO_LI_READY_PORT_L       $2142
.define TadIO_LI_READY_PORT_H       $2143
.define TadIO_LI_READY_PORT_HL      $2142
.define TadIO_LI_LOADER_READY_L     $4c
.define TadIO_LI_LOADER_READY_H     $44
.define TadIO_LI_LOADER_READY_HL    (TadIO_LI_LOADER_READY_L | (TadIO_LI_LOADER_READY_H << 8))

; --- Loader data transfer ---
.define TadIO_LD_DATA_PORT_L        $2141
.define TadIO_LD_DATA_PORT_H        $2142
.define TadIO_LD_SPINLOCK_PORT      $2143
.define TadIO_LD_SPINLOCK_MASK      $0f
.define TadIO_LD_SPINLOCK_COMPLETE  $80

; --- Loader data types ---
.define TadLoaderDataType_CODE                    0
.define TadLoaderDataType_COMMON_DATA             1
.define TadLoaderDataType_SONG_DATA_FLAG          $80
.define TadLoaderDataType_PLAY_SONG_FLAG          $40
.define TadLoaderDataType_RESET_GLOBAL_VOL_FLAG   $20
.define TadLoaderDataType_STEREO_FLAG             $02
.define TadLoaderDataType_SURROUND_FLAG           $01


; ========================
; Audio Data Binary Layout
; ========================
;
; Generated by tad-compiler. Update these after re-running the compiler.
; The binary file is: build/audio/tad-audio-data.bin

.define TAD_LOADER_SIZE         116
.define TAD_AUDIO_DRIVER_SIZE   3250
.define TAD_LOADER_OFFSET       0
.define TAD_AUDIO_DRIVER_OFFSET 116
.define TAD_DATA_TABLE_OFFSET   3366
.define TAD_DATA_TABLE_SIZE     8
.define TAD_N_DATA_ITEMS        2


; ==============
; WRAM Variables
; ==============
;
; TAD variables MUST be in lowram ($0000-$1FFF) so they are accessible
; from any bank via absolute addressing when DB=$80 (register bank).

.ramsection "TAD lowram vars" bank 0 slot 2
Tad_flags               db      ; TadFlags bitfield
Tad_audioMode            db      ; TadAudioMode enum
TadPriv_state           db      ; TadState
TadPriv_bytesPerFrame   dw      ; transfer bytes per Tad_Process
TadPriv_previousCommand db      ; previous APUIO0 sent to driver
TadPriv_xfer_addr       dw      ; far pointer: remaining data to transfer
TadPriv_xfer_bank       db
TadPriv_xfer_size       dw      ; remaining bytes to transfer
TadPriv_xfer_prevSpin   db      ; previous spinlock value
TadPriv_nextSong        db      ; next song to load
TadPriv_nextCmd_id      db      ; next command (negative = empty)
TadPriv_nextCmd_p0      db      ; command parameter 0
TadPriv_nextCmd_p1      db      ; command parameter 1
Tad_sfxQueue_sfx         db      ; next SFX id ($FF = empty)
Tad_sfxQueue_pan         db      ; SFX pan value
.ends


; ==================
; Audio Data in ROM
; ==================
;
; Embeds the TAD binary (loader + driver + audio data) into a superfree section.
; The LoadAudioData callback is included here and uses label arithmetic
; to compute absolute addresses (no bank-alignment requirement).

; tad-compiler's data-table entries are offsets relative to a "LoadAudioData
; code prefix" that it assumes sits before the bin in the same section (43
; bytes for HiROM 64tass-export). Our LoadAudioData lives elsewhere, so we
; pad the label `Tad_AudioData` 43 bytes ahead of the real bin start to
; realign what LoadAudioData computes with what the data table means.
.define TAD_BIN_DATA_OFFSET 43

.bank 2 slot 0
.base BSL
.section "TAD Audio Data" free
Tad_AudioData:
  .dsb TAD_BIN_DATA_OFFSET, $00
Tad_Loader_Bin:
  .incbin "build/audio/tad-audio-data.bin" SKIP TAD_LOADER_OFFSET READ TAD_LOADER_SIZE
Tad_AudioDriver_Bin:
  .incbin "build/audio/tad-audio-data.bin" SKIP TAD_AUDIO_DRIVER_OFFSET READ TAD_AUDIO_DRIVER_SIZE
Tad_DataTable:
  .incbin "build/audio/tad-audio-data.bin" SKIP TAD_DATA_TABLE_OFFSET
_Tad_AudioData_End:
.ends
