#!/usr/bin/env python3
"""Generate ROM costume data assembly file from converted costume directories.

Scans data/snes_converted/costumes/cost_NNN/ and generates:
  - CostumeDirTable: indexed by costume number -> palette ptr, frame count, frame table ptr
  - Per-costume FrameTable: indexed by pic index -> CHR ptr/bank/len, OAM ptr/bank
  - FILEINC sections for all CHR/OAM/palette binary data
  - Walk cycle table (shared across all humanoid costumes)

Output: src/data/costumes/costume_data.inc (assembly include file)

Usage:
    python tools/gen_costume_rom.py
"""

import json
import os
import sys
from pathlib import Path

# Add tools dir to path for imports
TOOLS_DIR = Path(__file__).parent
PROJECT_ROOT = TOOLS_DIR.parent
CONVERTED_DIR = PROJECT_ROOT / "data" / "snes_converted" / "costumes"
OUTPUT_DIR = PROJECT_ROOT / "src" / "data" / "costumes"
OUTPUT_FILE = OUTPUT_DIR / "costume_data.inc"

# Max costume number to support (MI1 has ~123 costumes)
MAX_COSTUME = 128

# Max pics per costume we'll include in ROM
MAX_PICS_PER_COSTUME = 50


def scan_costumes():
    """Scan converted costume directories and return dict of {costume_num: info}."""
    costumes = {}
    if not CONVERTED_DIR.exists():
        print(f"Warning: {CONVERTED_DIR} not found")
        return costumes

    for d in sorted(CONVERTED_DIR.iterdir()):
        if not d.is_dir() or not d.name.startswith("cost_"):
            continue
        try:
            num = int(d.name.split("_")[1])
        except (IndexError, ValueError):
            continue

        # Find all pic files
        pics = []
        for i in range(MAX_PICS_PER_COSTUME):
            chr_file = d / f"pic{i:02d}.chr"
            oam_file = d / f"pic{i:02d}.oam"
            if chr_file.exists() and oam_file.exists():
                json_file = d / f"pic{i:02d}.json"
                meta = {}
                if json_file.exists():
                    with open(json_file) as f:
                        meta = json.load(f)
                pics.append({
                    "index": i,
                    "chr_path": chr_file,
                    "oam_path": oam_file,
                    "chr_size": chr_file.stat().st_size,
                    "oam_size": oam_file.stat().st_size,
                    "meta": meta,
                })

        pal_file = d / "palette.pal"
        if not pal_file.exists() or not pics:
            continue

        costumes[num] = {
            "dir": d,
            "palette": pal_file,
            "pics": pics,
            "num_pics": len(pics),
        }

    return costumes


def rel_path(p):
    """Return path relative to project root, using forward slashes."""
    return str(p.relative_to(PROJECT_ROOT)).replace("\\", "/")


def generate_assembly(costumes):
    """Generate the assembly include file."""
    lines = []
    lines.append("; Auto-generated by tools/gen_costume_rom.py — DO NOT EDIT")
    lines.append("; Costume ROM data for multi-actor rendering")
    lines.append("")

    # Determine which costume numbers we have
    costume_nums = sorted(costumes.keys())
    print(f"Generating ROM data for {len(costume_nums)} costumes: {costume_nums}")

    # --- Walk cycle tables (per-direction, from costume 1 ANIM data) ---
    # Costume 1 (SCUMM ID 1) = standard Guybrush. 6-step walk per direction.
    # ROM pic indices account for NULL entries skipped at positions 1 and 22:
    #   North stand=pic0→ROM0, walk=pics2-7→ROM1-6
    #   South stand=pic8→ROM7, walk=pics9-14→ROM8-13
    #   East  stand=pic21→ROM20, walk=pics15-20→ROM14-19
    #   West  = East H-flipped by renderer
    lines.append(";===================================================================")
    lines.append("; Walk cycle tables (ROM pic index per animation step)")
    lines.append("; Index 0 = stand frame, indices 1-6 = walk cycle (costume 1)")
    lines.append(";===================================================================")
    lines.append(".section \"CostumeWalkCycle\" superfree")
    lines.append("CostumeWalkCycleNorth:                  ; north (rear view: pics 21,15-20)")
    lines.append("  .db 20, 14, 15, 16, 17, 18, 19")
    lines.append("CostumeWalkCycleSide:                   ; east/west (side view: pics 8,9-14)")
    lines.append("  .db 7, 8, 9, 10, 11, 12, 13")
    lines.append("CostumeWalkCycleFront:                  ; south (front view: pics 0,2-7)")
    lines.append("  .db 0, 1, 2, 3, 4, 5, 6")
    lines.append(".define COSTUME_WALK_CYCLE_LEN 7")
    lines.append(".define COSTUME_WALK_ANIM_SPEED 4")
    lines.append(".ends")
    lines.append("")

    # --- Per-costume data sections ---
    for num in costume_nums:
        info = costumes[num]
        prefix = f"Cost{num:03d}"
        pal_rel = rel_path(info["palette"])

        lines.append(f";===================================================================")
        lines.append(f"; Costume {num} — {info['num_pics']} pics")
        lines.append(f";===================================================================")
        lines.append(f".section \"{prefix}_Data\" superfree")
        lines.append("")

        # Palette
        lines.append(f"{prefix}_Pal:")
        lines.append(f'  .incbin "{pal_rel}"')
        lines.append("")

        # Frame lookup tables
        lines.append(f"; Frame CHR lookup (word addr, bank, length)")
        lines.append(f"{prefix}_ChrLo:")
        for pic in info["pics"]:
            lines.append(f"  .dw {prefix}_Pic{pic['index']:02d}_Chr")
        lines.append("")

        lines.append(f"{prefix}_ChrHi:")
        for pic in info["pics"]:
            lines.append(f"  .db :{prefix}_Pic{pic['index']:02d}_Chr")
        lines.append("")

        lines.append(f"{prefix}_ChrLen:")
        for pic in info["pics"]:
            lines.append(f"  .dw {prefix}_Pic{pic['index']:02d}_ChrEnd - {prefix}_Pic{pic['index']:02d}_Chr")
        lines.append("")

        lines.append(f"; Frame OAM lookup (word addr, bank)")
        lines.append(f"{prefix}_OamLo:")
        for pic in info["pics"]:
            lines.append(f"  .dw {prefix}_Pic{pic['index']:02d}_Oam")
        lines.append("")

        lines.append(f"{prefix}_OamHi:")
        for pic in info["pics"]:
            lines.append(f"  .db :{prefix}_Pic{pic['index']:02d}_Oam")
        lines.append("")

        # Frame data (CHR + OAM binary includes)
        for pic in info["pics"]:
            chr_rel = rel_path(pic["chr_path"])
            oam_rel = rel_path(pic["oam_path"])
            lines.append(f"{prefix}_Pic{pic['index']:02d}_Chr:")
            lines.append(f'  .incbin "{chr_rel}"')
            lines.append(f"{prefix}_Pic{pic['index']:02d}_ChrEnd:")
            lines.append(f"{prefix}_Pic{pic['index']:02d}_Oam:")
            lines.append(f'  .incbin "{oam_rel}"')
            lines.append("")

        lines.append(".ends")
        lines.append("")

    # --- Costume directory table ---
    # 8 bytes per entry: palLo(2) + palHi(1) + numPics(1) + frameTblLo(2) + frameTblHi(1) + pad(1)
    lines.append(";===================================================================")
    lines.append("; CostumeDirTable — indexed by costume number")
    lines.append("; 8 bytes per entry: palLo, palHi, numPics, pad, chrLoPtr, chrLoBank")
    lines.append("; Entry at offset = costume_number * 8")
    lines.append("; Unsupported costumes point to costume 1 (standard Guybrush) as fallback")
    lines.append(";===================================================================")
    lines.append('.section "CostumeDirTable" superfree')
    lines.append("")

    # Determine fallback costume (1 = standard walk Guybrush if available)
    fallback = 1 if 1 in costume_nums else (costume_nums[0] if costume_nums else None)

    costume_remap = {}

    lines.append("CostumeDirTable:")
    for i in range(MAX_COSTUME):
        num = costume_remap.get(i, i) if i in costumes or i in costume_remap else fallback
        if num is not None:
            prefix = f"Cost{num:03d}"
            n_pics = costumes[num]["num_pics"]
            lines.append(f"  ; costume {i}" + (f" -> fallback {num}" if i not in costumes else ""))
            lines.append(f"  .dw {prefix}_Pal")
            lines.append(f"  .db :{prefix}_Pal")
            lines.append(f"  .db {n_pics}")
            lines.append(f"  .dw {prefix}_ChrLo")
            lines.append(f"  .db :{prefix}_ChrLo")
            lines.append(f"  .db 0")
        else:
            lines.append(f"  ; costume {i} — no data")
            lines.append(f"  .dw 0")
            lines.append(f"  .db 0, 0")
            lines.append(f"  .dw 0")
            lines.append(f"  .db 0, 0")

    lines.append("")

    # OAM lookup table (same structure, separate for clarity)
    lines.append("CostumeDirOamTable:")
    for i in range(MAX_COSTUME):
        num = costume_remap.get(i, i) if i in costumes or i in costume_remap else fallback
        if num is not None:
            prefix = f"Cost{num:03d}"
            lines.append(f"  .dw {prefix}_OamLo")
            lines.append(f"  .db :{prefix}_OamLo")
            lines.append(f"  .db 0")
            lines.append(f"  .dw {prefix}_OamHi")
            lines.append(f"  .db :{prefix}_OamHi")
            lines.append(f"  .db 0")
        else:
            lines.append(f"  .dw 0, 0, 0, 0")

    lines.append("")
    lines.append(".ends")
    lines.append("")

    return "\n".join(lines) + "\n"


def main():
    costumes = scan_costumes()
    if not costumes:
        print("No converted costumes found!")
        sys.exit(1)

    print(f"Found {len(costumes)} converted costumes")
    for num, info in sorted(costumes.items()):
        total_chr = sum(p["chr_size"] for p in info["pics"])
        print(f"  cost_{num:03d}: {info['num_pics']} pics, "
              f"{total_chr:,} bytes CHR, {info['palette']}")

    asm = generate_assembly(costumes)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(asm)
    print(f"\nWrote {OUTPUT_FILE} ({len(asm):,} bytes)")


if __name__ == "__main__":
    main()
