#!/usr/bin/env python3
"""
Generate 256-entry SCUMM v5 opcode dispatch table for 65816.

Reads the OPCODE_MAP from tools/scumm/opcodes_v5.py and generates
a .dw table where each entry points to the handler label for that
opcode byte. Unimplemented opcodes point to op_stub.

Output: src/object/scummvm/scummvm_dispatch_table.inc
"""

import sys
from pathlib import Path

# Add tools/ to path so we can import the SCUMM module
sys.path.insert(0, str(Path(__file__).parent))

from scumm.opcodes_v5 import OPCODE_MAP

# Opcodes with real handlers in scummvm.65816
# Maps base opcode name -> handler label
IMPLEMENTED = {
    # Tier 1 — Boot critical
    'stopObjectCode':   'op_stopObjectCode',
    'breakHere':        'op_breakHere',
    'jumpRelative':     'op_jumpRelative',
    'move':             'op_move',
    'startScript':      'op_startScript',
    'stopScript':       'op_stopScript',
    # Tier 2 — Conditionals
    'isEqual':          'op_isEqual',
    'notEqualZero':     'op_notEqualZero',
    'equalZero':        'op_equalZero',
    'isNotEqual':       'op_isNotEqual',
    'isGreater':        'op_isGreater',
    'isLess':           'op_isLess',
    'isLessEqual':      'op_isLessEqual',
    'isGreaterEqual':   'op_isGreaterEqual',
    # Tier 3 — Arithmetic
    'add':              'op_add',
    'subtract':         'op_subtract',
    'increment':        'op_increment',
    'decrement':        'op_decrement',
    # Misc boot-path
    'setVarRange':      'op_setVarRange',
    'delay':            'op_delay',
    'delayVariable':    'op_delayVariable',
    'dummy':            'op_dummy',
    'cutscene':         'op_cutscene',
    'endCutscene':      'op_endCutscene',
    'override':         'op_override',
    'freezeScripts':    'op_freezeScripts',
    'stopObjectScript': 'op_stopObjectScript',
    'isScriptRunning':  'op_isScriptRunning',
    'debug':            'op_debug',
    'and':              'op_and',
    'or':               'op_or',
    'expression':       'op_expression',
    'chainScript':      'op_chainScript',
    'cursorCommand':    'op_cursorCommand',
    'systemOps':        'op_systemOps',
}


def generate_table(outpath: Path):
    lines = []
    lines.append('; Auto-generated by tools/gen_dispatch_table.py')
    lines.append('; 256-entry SCUMM v5 opcode dispatch table')
    lines.append('; Each .dw entry is a handler address for jsr (table,x)')
    lines.append('')
    lines.append('_scummvm.dispatchTable:')

    for i in range(256):
        name = OPCODE_MAP[i]
        handler = IMPLEMENTED.get(name, 'op_stub')
        lines.append(f'  .dw {handler:<28s} ; ${i:02X} {name}')

    lines.append('')

    outpath.parent.mkdir(parents=True, exist_ok=True)
    outpath.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(f"Generated {outpath} ({len(lines)} lines, 256 entries)")

    # Stats
    impl_set = set()
    stub_count = 0
    for i in range(256):
        name = OPCODE_MAP[i]
        if name in IMPLEMENTED:
            impl_set.add(name)
        else:
            stub_count += 1
    print(f"  Implemented base opcodes: {len(impl_set)}")
    print(f"  Stub entries: {stub_count}/256")


if __name__ == '__main__':
    project_root = Path(__file__).parent.parent
    outpath = project_root / 'src' / 'object' / 'scummvm' / 'scummvm_dispatch_table.inc'
    generate_table(outpath)
