"""Generate the SCUMM sound ID -> TAD audio map.

Walks data/scumm_extracted/sounds/*.bin, classifies each SOUN resource
(MIDI/SBL/ADL/stub), assigns TAD indices, and emits a WLA-DX .inc with
a 138-byte lookup table.

Byte encoding (SCUMM sound ID -> TAD dispatch):
    $FF         : no audio (stub or ADL-only — ADL can't run on SPC700)
    $00..$7F    : SFX index (use Tad_QueueSoundEffect)
    $80..$FE    : song index + $80 (use Tad_LoadSong)

Output:
    build/audio/scumm_sound_map.inc — WLA-DX section with ScummSoundMap label

The table is keyed by SCUMM sound ID, which matches the extraction order
in `data/scumm_extracted/sounds/soun_NNN_roomMMM.bin` (NNN = sound ID).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

SOUND_DIR = Path(__file__).resolve().parents[2] / "data" / "scumm_extracted" / "sounds"
DEFAULT_OUT = Path(__file__).resolve().parents[2] / "build" / "audio" / "scumm_sound_map.inc"

KIND_STUB = "stub"
KIND_MIDI = "midi"
KIND_SBL = "sbl"
KIND_ADL = "adl"
KIND_SPK = "spk"
KIND_UNKNOWN = "?"

SONG_FLAG = 0x80
NO_AUDIO = 0xFF
MAX_SONG_IDX = 0x7F
MAX_SFX_IDX = 0x7F


def classify(data: bytes) -> str:
    # Anything not wrapped in a recognizable SOU+<type> container is a stub —
    # SCUMM SOUN directory entries can be 24-byte placeholders with no audio.
    if len(data) < 12 or data[:4] != b"SOU ":
        return KIND_STUB
    tag = data[8:12]
    if tag == b"ROL ":
        return KIND_MIDI
    if tag == b"SBL ":
        return KIND_SBL
    if tag == b"ADL ":
        return KIND_ADL
    if tag == b"SPK ":
        return KIND_SPK
    return KIND_UNKNOWN


def build_map(sound_dir: Path) -> tuple[list[int], list[tuple[int, str, int | None]]]:
    files = sorted(sound_dir.glob("soun_*.bin"))
    if not files:
        raise SystemExit(f"no sound files under {sound_dir}")

    entries: list[tuple[int, str, int | None]] = []  # (scumm_id, kind, tad_idx)
    table: list[int] = [NO_AUDIO] * 256  # oversize then trim at end
    next_song = 0
    next_sfx = 0
    max_id = -1

    for path in files:
        # stem looks like soun_NNN_roomMMM
        stem = path.stem
        try:
            sid = int(stem.split("_")[1])
        except (IndexError, ValueError):
            print(f"skip {path.name}: can't parse sound id", file=sys.stderr)
            continue
        max_id = max(max_id, sid)
        data = path.read_bytes()
        kind = classify(data)
        if kind == KIND_MIDI:
            if next_song > MAX_SONG_IDX:
                raise SystemExit(f"too many songs (>{MAX_SONG_IDX})")
            table[sid] = SONG_FLAG | next_song
            entries.append((sid, kind, next_song))
            next_song += 1
        elif kind == KIND_SBL:
            if next_sfx > MAX_SFX_IDX:
                raise SystemExit(f"too many SFX (>{MAX_SFX_IDX})")
            table[sid] = next_sfx
            entries.append((sid, kind, next_sfx))
            next_sfx += 1
        else:
            entries.append((sid, kind, None))

    if max_id < 0:
        raise SystemExit("no valid sound files found")
    return table[: max_id + 1], entries


def emit_inc(out: Path, table: list[int], entries: list[tuple[int, str, int | None]]) -> None:
    n = len(table)
    songs = sum(1 for _, k, _ in entries if k == KIND_MIDI)
    sfx = sum(1 for _, k, _ in entries if k == KIND_SBL)
    stubs = sum(1 for _, k, _ in entries if k == KIND_STUB)
    adls = sum(1 for _, k, _ in entries if k == KIND_ADL)
    spks = sum(1 for _, k, _ in entries if k == KIND_SPK)

    lines: list[str] = []
    lines.append(";; Auto-generated by tools/scumm/gen_audio_map.py -- DO NOT EDIT.")
    lines.append(";;")
    lines.append(f";; SCUMM sound ID -> TAD dispatch ({n} entries).")
    lines.append(f";; Songs: {songs}  SFX: {sfx}  ADL-only: {adls}  SPK: {spks}  stubs: {stubs}")
    lines.append(";;")
    lines.append(";; Byte encoding:")
    lines.append(";;   $FF         : no audio (stub, AdLib-only, or PC Speaker)")
    lines.append(";;   $00..$7F    : SFX index (Tad_QueueSoundEffect)")
    lines.append(";;   $80..$FE    : song index | $80 (Tad_LoadSong)")
    lines.append("")
    lines.append('.section "ScummSoundMap" superfree')
    lines.append("ScummSoundMap:")

    # Emit 16 bytes per line with trailing comment showing ID range.
    for row_start in range(0, n, 16):
        row = table[row_start : row_start + 16]
        hex_vals = ", ".join(f"${b:02X}" for b in row)
        lines.append(f"  .db {hex_vals}  ; {row_start:3d}..{row_start + len(row) - 1:3d}")

    lines.append(".ends")
    lines.append("")

    # Manifest comment block at end for humans.
    lines.append(";; === Manifest ===")
    for sid, kind, tad in entries:
        if kind == KIND_MIDI:
            lines.append(f";; {sid:3d}  song {tad:3d}")
        elif kind == KIND_SBL:
            lines.append(f";; {sid:3d}   sfx {tad:3d}")
        elif kind == KIND_ADL:
            lines.append(f";; {sid:3d}   ADL (unplayable — silent)")
        elif kind == KIND_SPK:
            lines.append(f";; {sid:3d}   SPK (unplayable — silent)")
        else:
            lines.append(f";; {sid:3d}  stub")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--sound-dir", type=Path, default=SOUND_DIR)
    ap.add_argument("--output", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args()

    table, entries = build_map(args.sound_dir)
    emit_inc(args.output, table, entries)

    songs = sum(1 for _, k, _ in entries if k == KIND_MIDI)
    sfx = sum(1 for _, k, _ in entries if k == KIND_SBL)
    adls = sum(1 for _, k, _ in entries if k == KIND_ADL)
    spks = sum(1 for _, k, _ in entries if k == KIND_SPK)
    stubs = sum(1 for _, k, _ in entries if k == KIND_STUB)
    print(f"wrote {args.output}")
    print(f"  {len(table)} entries | songs={songs} sfx={sfx} adl={adls} spk={spks} stub={stubs}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
